### ISSUE TITLE
Why use Ant Design instead of Vue or React?

### ISSUE THREAD

**Issue by hsluoyz** [LyricTian/gin-admin#1]
I think Vue or React is more popular as a front-end framework than Ant Design. The users of your project will enlarge if you use those popular frameworks.

**Comment by LyricTian** [comment]
你好，本项目使用的是Ant Design的React版本，后面会把所有的API接口文档提供出来，允许定制自己的前端UI。

**Comment by hsluoyz** [comment]
Thanks for the answer. I would like to invite you to join Casbin's QQ group: 546057381

**Comment by LyricTian** [comment]
好的，谢谢。
