### ISSUE TITLE
v8版本uint64类型ID前端接收的问题

### ISSUE THREAD

**Issue by chenyu1990** [LyricTian/gin-admin#111]
目前js不支持大数，ID会丢失精度。
解决办法来自二楼

schema

	ID        uint64    `json:"id,string"`                    // 唯一标识

**Comment by dsjalje** [comment]
修改 tag

ID        uint64    `json:"id,string"`

**Comment by Choi-Keith** [comment]
ID uint64 `json:"id:string"`后出现Parse request json failed: json: invalid use of ,string struct tag, trying to unmarshal \"\" into uint64，请问该如何解决

**Comment by chenyu1990** [comment]
> ID uint64 `json:"id:string"`后出现Parse request json failed: json: invalid use of ,string struct tag, trying to unmarshal "" into uint64，请问该如何解决

你这细心程度，当程序员，确实有点难。符号打错了
