### ISSUE TITLE
v8 postgresql 不支持 tinyint

### ISSUE THREAD

**Issue by dsjalje** [LyricTian/gin-admin#112]
报错：
pkg/mod/gorm.io/driver/postgres@v1.1.0/migrator.go:157 ERROR: type "tinyint" does not exist (SQLSTATE 42704)

**Comment by Conight** [comment]
Use `smallint` while using postgresql.
[PostgreSQL: Documentation: 13: 8.1. Numeric Types](https://www.postgresql.org/docs/current/datatype-numeric.html)

**Comment by LyricTian** [comment]
done
