### ISSUE TITLE
TablePrefix没有生效

### ISSUE THREAD

**Issue by jianjianxu** [LyricTian/gin-admin#136]
V10版本，请教是为啥，打印了一下各种配置，没看出来问题在哪

**Comment by LyricTian** [comment]
Fixed, please review this commit, [fix: Fix table name prefix](https://github.com/LyricTian/gin-admin/commit/cf8080d487de4f94d25e932f9b0642ea062c9f9f)

**Comment by jianjianxu** [comment]
AutoMigrate 执行完建立的数据表还是不带前缀

**Comment by jianjianxu** [comment]
AutoMigrate 执行完建立的数据表还是不带前缀
