### ISSUE TITLE
Provide English version (UI, README)

### ISSUE THREAD

**Issue by hsluoyz** [LyricTian/gin-admin#2]
As you may know, Casbin have users from different countries. Most of them use English. I think it will be better for them to use this project if it provides English UI and documentation.

**Comment by LyricTian** [comment]
Ok, I will try to support the English version.

**Comment by Max-Pol** [comment]
Yes an English version would be great!

**Comment by somq** [comment]
Is there any further plan to make this happen ?
The README and the demo app are still in Chinese.

Does these pull requests actually refers to the issue or maybe the demo UI is outdated?
