### ISSUE TITLE
2.0版本二级菜单的BUG

### ISSUE THREAD

**Issue by rainggo** [LyricTian/gin-admin#23]
如下图，在1.2版本中，通过修改前端的限制后可以创建二级菜单，而功能选择是正常的。
![image](https://user-images.githubusercontent.com/20737412/56597772-bea7c580-6625-11e9-83ef-d183a2e40b28.png)

在2.0版本中，创建了二级菜单后，因为此处长度相同而导致无法选择二级菜单
![image](https://user-images.githubusercontent.com/20737412/56597836-e008b180-6625-11e9-9a6f-531c6b7f3f3b.png)

**Comment by rainggo** [comment]
通过对比新旧代码发现，1.2版本中使用的是level_code作为key，而二级菜单的level_code会比上一级的多2位。
而在2.0版本中，改用了record_id，而record_id是使用的uuid，长度是相同的，导致选择二级菜单后，菜单栏会出现没有选择任何菜单的情况

![image](https://user-images.githubusercontent.com/20737412/56598093-63c29e00-6626-11e9-887e-607319fd27a4.png)

**Comment by LyricTian** [comment]
嗯，该bug已经在新版本中修复，请查看：

**Comment by rainggo** [comment]
已经解决了，谢谢
