### ISSUE TITLE
GOCACHE is not defined 出现这个错误

### ISSUE THREAD

**Issue by lchjczw** [LyricTian/gin-admin#25]
`
$ make start

build cache is required, but could not be located: GOCACHE is not defined and %L ocalAppData% is not defined

make: *** [Makefile:15: start] Error 1
`
执行Makefile出错，但是我看了，这个编译代码，怎么会提示这个错误呢

**Comment by lchjczw** [comment]
我在环境变量里面设置了GOCACHE为一个路径，还是不行

**Comment by lchjczw** [comment]
这个地方是设置在golang里面，不过我在Windows下还是没有编译通过，应该是sqllite需要重新编译，我看除了需要gcc外，还需要动态链接库

**Comment by lchjczw** [comment]
还是我的姿势，哪里不太对？

**Comment by lchjczw** [comment]
找到问题了，Windows下编译sqlite有问题，估计在Linux和mac下是没有什么问题的
解决方法：安装完整版的tdm-gcc可以解决，安装mingw和msys是不行的，库不完整

**Comment by freeaswind** [comment]
> 找到问题了，Windows下编译sqlite有问题，估计在Linux和mac下是没有什么问题的 解决方法：安装完整版的tdm-gcc可以解决，安装mingw和msys是不行的，库不完整

![image](https://github.com/LyricTian/gin-admin/assets/13989977/826fa259-04ba-48cb-99a3-1fc61d282054)
我安装了这个也没解决啊  还是报同样的错误
愁啊
