### ISSUE TITLE
是否考虑把平滑重启加上?

### ISSUE THREAD

**Issue by JeffreyBool** [LyricTian/gin-admin#3]
是否考虑把平滑重启加上

**Comment by LyricTian** [comment]
嗯，有这个计划，在下一个版本迭代中会出现。

## v1.1.0

- 引入JWT的支持，提供参数配置，支持session与jwt
- 加入日志管理功能，支持日志查询及清理
- 加入接口管理功能，支持接口的CRUD，同时服务端支持动态注入接口
- 加入功能组管理功能，将现有的菜单管理改名为功能组管理，同时支持批量选择接口
- 引入Swagger的支持，可提供一整套完整的接口文档
- 引入CORS中间件，可作为参数项配置，支持跨域
- 引入静态文件服务中间件，可作为命令行参数项，提供静态文件服务
- 引入请求频次限制中间件，支持GET/POST的请求频次限制，同时支持白名单功能，可接入redis/memory
- 提供HTTP优雅重启的支持，具体参考：<https://github.com/fvbock/endless>

**Comment by hpze2000** [comment]
@LyricTian 大佬，牛逼了，正好用上， 不过1.2.0 有计划么， 想用 gorm。

**Comment by LyricTian** [comment]
gorm版本争取本周完成 @hpze2000

**Comment by LyricTian** [comment]
2.0版本已经发布
