### ISSUE TITLE
代码很好，就是结构太多太复杂

### ISSUE THREAD

**Issue by Thunural** [LyricTian/gin-admin#39]
首先感谢作者开源。目前发现阅读起来太困难。代码结构目录层级太多。梳理逻辑关系上手太困难。

**Comment by lmdkfs** [comment]
我这几天在看这个项目，写的不错，里面用dig的依赖注册，这块没搞明白，有些复杂。

**Comment by huapox** [comment]
code complex +1

**Comment by dyzsoft** [comment]
code complex +1

**Comment by birdycn** [comment]
code complex +1
