### ISSUE TITLE
github.com/LyricTian/captcha

### ISSUE THREAD

**Issue by pythonsite** [LyricTian/gin-admin#57]
您好，在看您的代码的时候发现您仓库中github.com/LyricTian/captcha 这个代码和您vendor中的github.com/LyricTian/captcha  并不是一致的，可以更改成一致的么，还是说出于其他考虑没有更改，我这边直接用的go module 做的包管理，所以直接是go get github.com/LyricTian/captcha  但是包里是缺少redis_options.go 文件的

**Comment by LyricTian** [comment]
已经升级所有依赖模块和vendor包，请查看5.2.1版本

**Comment by pythonsite** [comment]
好的谢谢
