### ISSUE TITLE
多机器部署，权限不能统一

### ISSUE THREAD

**Issue by chrisfeng0723** [LyricTian/gin-admin#75]
在多机器部署的时候，会造成权限不统一，能否考虑将casbin的Watcher引入？

**Comment by LyricTian** [comment]
这块是支持的，可以在配置中启用该配置：
```
# casbin配置
[casbin]
# 是否启用casbin
enable = true
# debug模式
debug = false
# 模型配置文件(也可以启动服务时使用-m指定)
model = ""
# 是否启用定期自动加载策略
auto_load = false
# 定期自动加载策略时间间隔（单位秒）
auto_load_internal = 10
```

**Comment by chrisfeng0723** [comment]
目前采用的方式是定期加载，但是需要多次去刷新数据库处理。想着是否有更合理的办法。

**Comment by chrisfeng0723** [comment]
> 这块是支持的，可以在配置文件中启用该配置：
> 
> ```
> # casbin配置
> [casbin]
> # 是否启用casbin
> enable = true
> # debug模式
> debug = false
> # 模型配置文件(也可以启动服务时使用-m指定)
> model = ""
> # 是否启用定期自动加载策略
> auto_load = false
> # 定期自动加载策略时间间隔（单位秒）
> auto_load_internal = 10
> ```

目前采用的方式是定期加载，但是需要多次去刷新数据库处理。想着是否有更好办法？

**Comment by LyricTian** [comment]
可以接入通知机制实时更新，采用类似kafka的发布、订阅机制，服务更新权限之后，通知到所有关联服务

**Comment by GanymedeNil** [comment]
casbin 可以通过etcd 等做分布式同步
