### ISSUE TITLE
编译运行时候提示资源不存在？

### ISSUE THREAD

**Issue by pt00ls** [LyricTian/gin-admin#8]
$ ./server -c ../../config/config.toml -m ../../config/model.conf
开始运行服务，服务版本号：1.2.0-dev
INFO[0000] 服务已运行在[test]模式下，运行版本:1.2.0-dev，进程号：8878       span_function= span_id=61b97f94-b06d-418e-8f1f-5882e8851c0e span_title= started_at="2019-01-16 10:47:40.631298875 +0800 CST m=+0.105783090" trace_id=cdb4c6b1-f010-4ca3-8d17-d721afe353ba user_id=
INFO[0000] HTTP服务开始启动，监听地址为：[127.0.0.1:8086]             span_function= span_id=1b38453f-12c3-43cb-bd02-6d63b484a4cf span_title= started_at="2019-01-16 10:47:40.63526605 +0800 CST m=+0.109750342" trace_id=cdb4c6b1-f010-4ca3-8d17-d721afe353ba user_id=
WARN[0009] [请求错误] 资源不存在

**Comment by LyricTian** [comment]
你这个错误是发生在运行之后，在浏览器里面访问地址的时候吧？

**Comment by pt00ls** [comment]
您好，请问运行时使用参数-wwww指定前端编译后的dist目录，是指yarn运行指定吗，好像yarn没看到www参数？

**Comment by pt00ls** [comment]
是的 ，我已经看到您的答复，需要编译下前端项目，我已经重新编译前端项目文件web生成dist文件,如下
[cid:image001.png@01D4ADCC.3210C340]
但是不知道如何使用www参数指定dist运行，还请指教？感谢了

发件人: Lyric <notifications@github.com>
答复: LyricTian/gin-admin <reply@reply.github.com>
日期: 2019年1月16日 星期三 上午11:14
收件人: LyricTian/gin-admin <gin-admin@noreply.github.com>
抄送: 0rg <secure0rg@outlook.com>, Author <author@noreply.github.com>
主题: Re: [LyricTian/gin-admin] 编译运行时候提示资源不存在？ (#8)


你这个错误是发生在运行之后，在浏览器里面访问地址的时候吧？

**Comment by LyricTian** [comment]
尝试执行命令：
```
./server -c ../../config/config.toml -m ../../config/model.conf -www ../../web/dist
```

**Comment by pt00ls** [comment]
非常感谢，成功解决了
