### ISSUE TITLE
v2.0.0版本功能列表

### ISSUE THREAD

**Issue by LyricTian** [LyricTian/gin-admin#9]
- 重构服务端代码，实现业务逻辑和存储完全分离，提供统一的事务处理上下文和完整的日志跟踪
- 加入gorm存储层的支持
- 加入日志管理功能，支持日志查询及清理
- 加入接口管理功能，支持服务端动态注入
- 加入查询个人信息及修改个人密码的功能
- 菜单管理支持以选择接口的方式批量增加资源
- 引入JWT认证的支持，提供参数配置，支持session与jwt
- 引入Swagger的支持，可提供一整套完整的接口文档
- 引入CORS中间件，可作为参数项配置，支持跨域
- 引入静态文件服务中间件，可作为命令行参数项，提供静态文件服务
- 引入请求频次限制中间件，支持GET/POST的请求频次限制，可接入memory/redis
- 提供HTTP优雅重启的支持
- 用户登录增加图形验证码的支持，支持memory/redis存储

**Comment by JeffreyBool** [comment]
什么时候发布2.0

**Comment by LyricTian** [comment]
预计这两周内可以开发完成，最新版本可以查看develop分支：

**Comment by JeffreyBool** [comment]
2.0 具体啥时候发布呀

**Comment by locxiang** [comment]
> 2.0 具体啥时候发布呀

不是说了两周内吗？骚男
