### ISSUE TITLE
user role map转换问题

### ISSUE THREAD

**Issue by lihong12500** [LyricTian/gin-admin#98]
描述：
// ToMap 转换为map
func (a UserRoles) ToMap() map[string]*UserRole {
	m := make(map[string]*UserRole)
	for _, item := range a {
		m[item.RoleID] = item
	}
	return m
}
我理解的是一个角色ID对应一条数据userrole,如果一个用户多个角色，同时一个角色也能赋值给多个用户，那么roleID不是唯一的。。。。是否有问题？

**Comment by Conight** [comment]
这个方法的使用场景只有在 `compareUserRoles` 方法中
```go
mOldUserRoles := oldUserRoles.ToMap()
mNewUserRoles := newUserRoles.ToMap()
```

而这个方法只会传过来某一个用户的 `roles`，所以不会存在覆盖问题。
